/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NElement: typeof import('naive-ui')['NElement']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WCap: typeof import('@/components/Global/Cap/index.ts')['default']
    WReloadPrompt: typeof import('@/components/Global/ReloadPrompt/index.ts')['default']
    WTransition: typeof import('@/components/Extra/Transition/index.ts')['default']
    WVerifyAuth: typeof import('@/components/Global/VerifyAuth/index.ts')['default']
  }
}

// For TSX support
declare global {
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NElement: typeof import('naive-ui')['NElement']
  const NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
  const NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const WCap: typeof import('@/components/Global/Cap/index.ts')['default']
  const WReloadPrompt: typeof import('@/components/Global/ReloadPrompt/index.ts')['default']
  const WTransition: typeof import('@/components/Extra/Transition/index.ts')['default']
  const WVerifyAuth: typeof import('@/components/Global/VerifyAuth/index.ts')['default']
}