import type { Ref } from 'vue'
import { useIntervalFn, watchThrottled } from '@vueuse/core'
import { computed, nextTick, onMounted, onUnmounted, ref } from 'vue'

/**
 * Generated by Doubao, optimised by me
 * Create a timer with percentage tracking.
 * @param durationRef Total duration of one timer cycle in milliseconds, supports reactive Ref
 * @param callback Invoked once per completed cycle
 */
export function useIntervalFnWithPercent(
  durationRef: Ref<number>,
  callback: () => void,
) {
  const PERCENT_INTERVAL = 33 // Frequency of elapsed-time updates in ms

  const flag = ref(true)
  const startTime = ref<number | undefined>(undefined)
  const elapsed = ref(0)

  const percentage = computed(() =>
    +Math.min(100, (elapsed.value / durationRef.value) * 100).toFixed(2),
  )

  // Sync elapsed time against wall clock, guarding against large gaps (e.g. after tab suspension)
  const updateTime = () => {
    const now = Date.now()

    if (!startTime.value) {
      startTime.value = now
      return
    }

    const delta = now - startTime.value - elapsed.value
    if (delta < 1000) {
      elapsed.value += delta
    }
  }

  const timeControls = useIntervalFn(callback, durationRef, { immediate: true })
  const percentControls = useIntervalFn(updateTime, PERCENT_INTERVAL, { immediateCallback: true })

  const isActive = computed(() => timeControls.isActive.value && percentControls.isActive.value)

  // Reset when a full cycle completes; use nextTick to let dependents react to percentage = 100 first
  watchThrottled(
    percentage,
    (v) => {
      if (v < 100)
        return
      flag.value = false
      nextTick(() => {
        reset()
        flag.value = true
      })
    },
    { throttle: 250, immediate: true },
  )

  function start() {
    timeControls.resume()
    percentControls.resume()
  }

  // Clearing startTime ensures delta restarts cleanly on the next resume
  function pause() {
    timeControls.pause()
    percentControls.pause()
    startTime.value = undefined
  }

  // reset has different semantics from pause: it stops, clears state, and immediately restarts.
  // Inlining the stop step avoids inheriting pause's side-effects.
  function reset() {
    timeControls.pause()
    percentControls.pause()
    startTime.value = undefined
    elapsed.value = 0
    start()
  }

  onMounted(start)
  onUnmounted(pause)

  return { start, pause, flag, percentage, elapsed, isActive }
}
